# Autogenerated wrapper script for SoapyRemote_jll for x86_64-apple-darwin
export libremoteSupport

using soapysdr_jll
JLLWrappers.@generate_wrapper_header("SoapyRemote")
JLLWrappers.@declare_library_product(libremoteSupport, "libremoteSupport.dylib")
function __init__()
    JLLWrappers.@generate_init_header(soapysdr_jll)
    JLLWrappers.@init_library_product(
        libremoteSupport,
        "lib/SoapySDR/modules0.8/libremoteSupport.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
